version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "dash"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  lint:
    summary: Run golangci-lint on the Go codebase
    cmds:
      - golangci-lint run

  lint:fix:
    summary: Run golangci-lint with auto-fixing
    cmds:
      - golangci-lint run --fix

  lint:new:
    summary: Run golangci-lint only on new/changed code
    cmds:
      - golangci-lint run --new-from-rev=HEAD~1

  test:
    summary: Run all Go tests
    cmds:
      - go test ./pkg/...

  test:coverage:
    summary: Run tests with coverage report
    cmds:
      - go test ./pkg/... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  fmt:
    summary: Format Go code using go fmt
    cmds:
      - go fmt ./...

  check:
    summary: Run all quality checks (test + lint)
    deps:
      - test
      - lint

