version: '3'

vars:
  APP_NAME: "dash"
  BIN_DIR: "bin"

tasks:
  build:
    summary: Builds the application
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - |
        {{if eq OS "linux"}}
        go build --tags nowayland -o {{.BIN_DIR}}/{{.APP_NAME}}{{exeExt}} main.go
        {{else}}
        go build -o {{.BIN_DIR}}/{{.APP_NAME}}{{exeExt}} main.go
        {{end}}

  run:
    summary: Runs the application
    cmds:
      - go run main.go

  dev:
    summary: Runs the application in development mode
    cmds:
      - go run main.go

  lint:
    summary: Run golangci-lint on the Go codebase
    cmds:
      - golangci-lint run

  lint:fix:
    summary: Run golangci-lint with auto-fixing
    cmds:
      - golangci-lint run --fix

  lint:new:
    summary: Run golangci-lint only on new/changed code
    cmds:
      - golangci-lint run --new-from-rev=HEAD~1

  test:
    summary: Run all Go tests
    cmds:
      - go test ./pkg/...

  test:coverage:
    summary: Run tests with coverage report
    cmds:
      - go test ./pkg/... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  fmt:
    summary: Format Go code using go fmt
    cmds:
      - go fmt ./...

  check:
    summary: Run all quality checks (test + lint)
    deps:
      - test
      - lint

  clean:
    summary: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

