// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetDashboardData(): $CancellablePromise<string> {
    return $Call.ByID(550438918);
}

export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(3284817101);
}

export function SetLightBrightness(widgetID: string, brightness: number): $CancellablePromise<void> {
    return $Call.ByID(2522601653, widgetID, brightness);
}

export function TriggerWidget(widgetID: string): $CancellablePromise<void> {
    return $Call.ByID(472610134, widgetID);
}
