name: Build Cross-Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
          - os: ubuntu-24.04-arm
            platform: linux
            arch: arm64
          - os: macos-latest
            platform: darwin
            arch: amd64
          - os: macos-latest
            platform: darwin
            arch: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: false

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential pkg-config libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libxkbcommon-dev libvulkan-dev

      - name: Install Task
        run: |
          if ! command -v task &> /dev/null; then
            go install github.com/go-task/task/v3/cmd/task@latest
          fi

      - name: Build binary
        run: |
          mkdir -p bin
          if [ "${{ matrix.platform }}" = "linux" ]; then
            go build --tags nowayland -o bin/dash-${{ matrix.platform }}-${{ matrix.arch }} main.go
          else
            go build -o bin/dash-${{ matrix.platform }}-${{ matrix.arch }} main.go
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dash-${{ matrix.platform }}-${{ matrix.arch }}
          path: bin/dash-${{ matrix.platform }}-${{ matrix.arch }}*
          retention-days: 30
