name: Build Cross-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
          - os: ubuntu-24.04-arm
            platform: linux
            arch: arm64
          - os: macos-latest
            platform: darwin
            arch: amd64
          - os: macos-latest
            platform: darwin
            arch: arm64
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Linux dependencies
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev
    
    - name: Cache Go binaries
      uses: actions/cache@v4
      with:
        path: ~/go/bin
        key: go-binaries-${{ runner.os }}-${{ runner.arch }}
        restore-keys: go-binaries-${{ runner.os }}-
    
    - name: Install Task
      run: |
        if ! command -v task &> /dev/null; then
          go install github.com/go-task/task/v3/cmd/task@latest
        fi
    
    - name: Install Wails v3
      run: |
        if ! command -v wails3 &> /dev/null; then
          go install github.com/wailsapp/wails/v3/cmd/wails3@latest
        fi
    
    - name: Build binary
      env:
        GOARCH: ${{ matrix.arch }}
      run: task build PRODUCTION=true
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dash-${{ matrix.platform }}-${{ matrix.arch }}
        path: bin/dash*
        retention-days: 30